### ISSUE TITLE
SettingsExampleFragment.PrefFragment must be a public static class to be  properly recreated from instance state

### ISSUE THREAD

**Issue by g123k** [android/tv-samples#13]
Hello,

I was running the LeanbackShowcase app in an Android 10 (or Q) emulator.
Suddently when I have clicked on the Settings item, the app just crashed with the following error:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.persistence, PID: 15502
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.android.persistence/androidx.leanback.leanbackshowcase.app.settings.SettingsExampleActivity}: android.view.InflateException: Binary XML file line #20: Binary XML file line #20: Error inflating class fragment
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3102)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3237)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:81)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1929)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:209)
        at android.app.ActivityThread.main(ActivityThread.java:7021)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872)
     Caused by: android.view.InflateException: Binary XML file line #20: Binary XML file line #20: Error inflating class fragment
     Caused by: android.view.InflateException: Binary XML file line #20: Error inflating class fragment
     Caused by: java.lang.IllegalStateException: Fragment androidx.leanback.leanbackshowcase.app.settings.SettingsExampleFragment.PrefFragment must be a public static class to be  properly recreated from instance state.
        at android.app.BackStackRecord.doAddOp(BackStackRecord.java:429)
        at android.app.BackStackRecord.add(BackStackRecord.java:419)
        at androidx.leanback.preference.LeanbackSettingsFragment.startPreferenceFragment(LeanbackSettingsFragment.java:153)
        at androidx.leanback.leanbackshowcase.app.settings.SettingsExampleFragment.onPreferenceStartInitialScreen(SettingsExampleFragment.java:38)
        at androidx.leanback.preference.LeanbackSettingsFragment.onViewCreated(LeanbackSettingsFragment.java:78)
        at android.app.FragmentManagerImpl.ensureInflatedFragmentView(FragmentManager.java:1496)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1274)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1486)
        at android.app.FragmentManagerImpl.addFragment(FragmentManager.java:1728)
        at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:3562)
        at android.app.FragmentController.onCreateView(FragmentController.java:104)
        at android.app.Activity.onCreateView(Activity.java:6804)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:987)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:917)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:881)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1041)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1002)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:665)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:517)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:464)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:429)
        at android.app.Activity.setContentView(Activity.java:3238)
        at androidx.leanback.leanbackshowcase.app.settings.SettingsExampleActivity.onCreate(SettingsExampleActivity.java:28)
        at android.app.Activity.performCreate(Activity.java:7650)
        at android.app.Activity.performCreate(Activity.java:7639)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1295)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3077)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3237)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:81)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1929)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:209)
        at android.app.ActivityThread.main(ActivityThread.java:7021)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872)
```

**Comment by IanGClifton** [comment]
Confirmed. PrefFragment needs to be updated to be public and static so the FragmentManager can recreate it on demand.

**Comment by IanGClifton** [comment]
Just added in the fix for this. Thank you for reporting it!
