### ISSUE TITLE
[Leanback] Header State initialized with `HEADERS_HIDDEN` cause Fragment.getView() to not be null

### ISSUE THREAD

**Issue by drayan85** [android/tv-samples#19]
## Expected Behavior

Reference:
- [`Leanback` Android Application project](https://github.com/android/tv-samples/tree/master/Leanback)
- [`com.example.android.tvleanback.ui.MainFragment.java`](https://github.com/android/tv-samples/blob/master/Leanback/app/src/main/java/com/example/android/tvleanback/ui/MainFragment.java#L146)

App launched with `setHeaderState(HEADERS_HIDDEN)` should hide the header and still display the rows.

## Current Behavior

On app launched, it is not displaying any items in the `MainFragment.java`.

Pressing anything else on the D-pad (e.g. Press down), it will crash the app with the logs below: 

```
2020-01-10 18:23:40.662 32294-32294/com.example.android.tvleanback E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.tvleanback, PID: 32294
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View androidx.fragment.app.Fragment.getView()' on a null object reference
        at androidx.leanback.app.BrowseSupportFragment$4.onFocusSearch(BrowseSupportFragment.java:1096)
        at androidx.leanback.widget.BrowseFrameLayout.focusSearch(BrowseFrameLayout.java:118)
        at android.view.ViewGroup.focusSearch(ViewGroup.java:967)
        at android.view.View.focusSearch(View.java:10171)
        at android.view.ViewRootImpl$ViewPostImeInputStage.performFocusNavigation(ViewRootImpl.java:4664)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4782)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4605)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4200)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4166)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4293)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4174)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4350)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4200)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4166)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4174)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4200)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4166)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4326)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4487)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2435)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1998)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1989)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2412)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

### Note
Pressing left D-pad will open the Header and start to display the items.

## Steps to Reproduce (for bugs)

In https://github.com/android/tv-samples/blob/master/Leanback/app/src/main/java/com/example/android/tvleanback/ui/MainFragment.java#L146

Change `setHeadersState(HEADERS_ENABLED);` to `setHeadersState(HEADERS_HIDDEN);`

```diff
    private void setupUIElements() {
        setBadgeDrawable(
                getActivity().getResources().getDrawable(R.drawable.videos_by_google_banner, null));
        setTitle(getString(R.string.browse_title)); // Badge, when set, takes precedent over title
-       setHeadersState(HEADERS_ENABLED);
+       setHeadersState(HEADERS_HIDDEN);
        setHeadersTransitionOnBackEnabled(true);
```

## Context

We would like to launch the App without the header.

## Your Environment

Build
- Compiled Android SDK version 28
- `androidx.leanback:leanback:1.0.0`

Running on
- Android version 8.1.0
- Xiaomi TV-box (Android TV)

**Comment by IanGClifton** [comment]
Thank you for the detailed report! I've confirmed this issue and also verified it happens on other devices, with leanback 1.0.0 and 1.1.0-alpha03, whether setHeadersState(HEADERS_HIDDEN) is called in onActivityCreated or onViewCreated.

**Comment by drayan85** [comment]
Hi @IanGClifton, 

Thanks for the confirmation!

Do you have any insight if this issue will be fixed soon? or is there any workaround?

**Comment by IanGClifton** [comment]
It will probably be a while before this can be addressed. If you create your adapter and call setAdapter with it before the BrowseSupportFragment's onCreateView is called, it should have a valid mMainFragment reference and avoid the crash. You may have to then put your setHeadersState call after onCreateView is called (either by overriding onCreateView and holding the results locally temporarily or maybe just in onViewCreated).

**Comment by IanGClifton** [comment]
Note, I've also filed this at https://issuetracker.google.com/issues/147614095

**Comment by JCarlosR** [comment]
I see this issue still happens with `androidx.leanback:leanback:1.1.0-alpha04`.

**Comment by rsmbovct** [comment]
I found same problem in androidx.leanback:leanback:1.1.0-alpha05. Any update on the issue?

**Comment by IanGClifton** [comment]
Closing in favor of tracking at https://issuetracker.google.com/issues/147614095
